name: deploy to Surge

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "surge"
  cancel-in-progress: true

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: projet/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name : Build the project
        run: npm run build
      - name : Install Surge
        run: npm install --global surge
      - name: Deploy
        run : surge --project ./dist --domain aurelie-portfolio.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}