name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install
        working-directory: frontend-librairie

      - name: Build du projet
        run: npm run build
        working-directory: frontend-librairie

      - name: Déploiement sur GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend-librairie/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Déploiement sur GitHub Pages
        uses: actions/deploy-pages@v4
