name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write

  id-token: write

jobs:
  # Job pour construire le projet
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape pour récupérer le code du dépôt
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Étape pour configurer Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 16  # Assurez-vous que la version correspond à celle requise par Vite

      # Étape pour installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape pour construire le projet avec Vite
      - name: Build the project
        run: npm run build

      # Étape pour uploader les artefacts générés
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist  # Vite génère le site statique dans le dossier `dist`

  # Job pour déployer les artefacts sur GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Étape pour déployer le site sur GitHub Pages
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5