name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances (si nécessaire, par ex. pour React ou Next.js)
      - name: Install dependencies
        run: |
          cd /frontend-librairie/
          npm install

      # Étape 3 : Construire le projet
      - name: Build the project
        run: |
          npm run build

      # Étape 4 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Chemin vers le dossier contenant les fichiers statiques
